#This is a configuration file for CI integration using circle CI
version: 2
jobs:
  build:
    working_directory: ~/project
    docker:
      - image: circleci/android:api-25-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}
       #This downloads all the dependencies specified in the build gradle file from jcenter(), google() you name it
      - run:
          name: Export TERM and Download Dependencies
          command: export TERM=xterm && ./gradlew androidDependencies
       #Caching can significantly decrease the build time and reduce the limited build time credits from exhaustion
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}
        #This runs all the Unit Test
      - run:
          name: Build Project
          command: export TERM=xterm && ./gradlew build
